import type { MediaPlan } from './types';

/**
 * Dummy Media Plans Data
 * Sample media plans for testing the media planning feature
 */

export const dummyMediaPlans: MediaPlan[] = [
  {
    id: 'mp-001',
    campaignName: 'Summer Fashion Launch 2024',
    clientName: 'Fashion Forward Ltd',
    campaignObjective: 'Brand Awareness',
    targetAudience: 'Women aged 25-45, urban professionals',
    expectedStartDate: '2024-06-01',
    expectedEndDate: '2024-06-30',
    totalBudget: 150000,
    budgetAllocated: 120000,
    status: 'active',
    channels: [
      {
        mediaType: 'FM',
        channelName: 'Heaven Media House',
        segments: [
          {
            adType: 'ANNOUNCEMENTS',
            segmentClass: 'A1',
            segmentName: 'Prime Time',
            timeSlot: '06:00 - 10:00, 17:00 - 20:00',
            days: ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY'],
            unitRate: 5000,
            totalSpots: 20,
            rateCardId: 'rc-fm-announcements-001',
          },
          {
            adType: 'JINGLES',
            segmentClass: 'A1',
            segmentName: 'Peak Jingle',
            timeSlot: '06:00 - 12:00, 16:00 - 21:00',
            days: ['SATURDAY', 'SUNDAY'],
            unitRate: 4500,
            totalSpots: 10,
            rateCardId: 'rc-fm-jingles-002',
          },
        ],
      },
    ],
    createdAt: '2024-04-15T10:30:00Z',
    updatedAt: '2024-05-20T14:00:00Z',
  },
  {
    id: 'mp-002',
    campaignName: 'Tech Product Launch Q2',
    clientName: 'InnovateTech Ghana',
    campaignObjective: 'Product Launch',
    targetAudience: 'Tech enthusiasts, age 20-40, middle to high income',
    expectedStartDate: '2024-07-01',
    expectedEndDate: '2024-07-31',
    totalBudget: 250000,
    budgetAllocated: 200000,
    status: 'pending_approval',
    channels: [
      {
        mediaType: 'TV',
        channelName: 'Heaven Media House',
        segments: [
          {
            adType: 'SPOT_ADVERTS',
            segmentClass: 'PREMIUM',
            segmentName: 'Prime Time Spot',
            timeSlot: '19:00 - 22:00',
            days: ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY'],
            unitRate: 15000,
            totalSpots: 14,
            adForm: '30_SECS',
            rateCardId: 'rc-tv-spot-004',
            programName: 'Evening News',
          },
        ],
      },
      {
        mediaType: 'FM',
        channelName: 'Heaven Media House',
        segments: [
          {
            adType: 'INTERVIEWS',
            segmentClass: 'P',
            segmentName: 'Morning Interview',
            timeSlot: '07:00 - 09:00',
            days: ['WEDNESDAY'],
            unitRate: 8000,
            totalSpots: 2,
            rateCardId: 'rc-fm-interviews-003',
            programName: 'Morning Tech Talk',
          },
        ],
      },
    ],
    createdAt: '2024-05-01T09:00:00Z',
    updatedAt: '2024-05-28T16:30:00Z',
  },
  {
    id: 'mp-003',
    campaignName: 'Holiday Season Sale',
    clientName: 'SuperMart Retail',
    campaignObjective: 'Sales Conversion',
    targetAudience: 'General public, families, bargain shoppers',
    expectedStartDate: '2024-12-01',
    expectedEndDate: '2024-12-31',
    totalBudget: 180000,
    budgetAllocated: 90000,
    status: 'draft',
    channels: [
      {
        mediaType: 'FM',
        channelName: 'Heaven Media House',
        segments: [
          {
            adType: 'ANNOUNCEMENTS',
            segmentClass: 'A',
            segmentName: 'Standard',
            timeSlot: '10:00 - 17:00',
            days: ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY'],
            unitRate: 3000,
            totalSpots: 30,
            rateCardId: 'rc-fm-announcements-001',
          },
        ],
      },
    ],
    createdAt: '2024-05-25T11:00:00Z',
    updatedAt: '2024-05-25T11:00:00Z',
  },
  {
    id: 'mp-004',
    campaignName: 'Banking Services Awareness',
    clientName: 'TrustBank Ghana',
    campaignObjective: 'Lead Generation',
    targetAudience: 'Adults 30-60, business owners, working professionals',
    expectedStartDate: '2024-08-01',
    expectedEndDate: '2024-09-30',
    totalBudget: 300000,
    budgetAllocated: 300000,
    status: 'approved',
    channels: [
      {
        mediaType: 'TV',
        channelName: 'Heaven Media House',
        segments: [
          {
            adType: 'DOCUMENTARY',
            segmentClass: 'PREMIUM',
            segmentName: 'Prime Documentary',
            timeSlot: '20:00 - 21:30',
            days: ['SATURDAY', 'SUNDAY'],
            unitRate: 25000,
            totalSpots: 8,
            adForm: '60_SECS',
            rateCardId: 'rc-tv-documentary-005',
            programName: 'Business Success Stories',
          },
          {
            adType: 'SPOT_ADVERTS',
            segmentClass: 'M1',
            segmentName: 'Daytime Spot',
            timeSlot: '09:00 - 17:00',
            days: ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY'],
            unitRate: 8000,
            totalSpots: 25,
            adForm: '30_SECS',
            rateCardId: 'rc-tv-spot-004',
          },
        ],
      },
    ],
    createdAt: '2024-04-10T08:00:00Z',
    updatedAt: '2024-06-05T10:00:00Z',
  },
  {
    id: 'mp-005',
    campaignName: 'Health Insurance Enrollment',
    clientName: 'HealthFirst Insurance',
    campaignObjective: 'Engagement',
    targetAudience: 'Adults 25-65, all income levels',
    expectedStartDate: '2024-05-15',
    expectedEndDate: '2024-05-31',
    totalBudget: 80000,
    budgetAllocated: 80000,
    status: 'completed',
    channels: [
      {
        mediaType: 'FM',
        channelName: 'Heaven Media House',
        segments: [
          {
            adType: 'ANNOUNCEMENTS',
            segmentClass: 'A1',
            segmentName: 'Prime Time',
            timeSlot: '06:00 - 10:00, 17:00 - 20:00',
            days: ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY'],
            unitRate: 5000,
            totalSpots: 16,
            rateCardId: 'rc-fm-announcements-001',
          },
        ],
      },
    ],
    createdAt: '2024-04-01T12:00:00Z',
    updatedAt: '2024-06-01T15:00:00Z',
  },
  {
    id: 'mp-006',
    campaignName: 'Educational Platform Promotion',
    clientName: 'LearnHub Online',
    campaignObjective: 'Brand Awareness',
    targetAudience: 'Students, parents, educators, age 16-50',
    expectedStartDate: '2024-09-01',
    expectedEndDate: '2024-09-30',
    totalBudget: 120000,
    budgetAllocated: 60000,
    status: 'draft',
    channels: [
      {
        mediaType: 'TV',
        channelName: 'Heaven Media House',
        segments: [
          {
            adType: 'ANNOUNCEMENTS',
            segmentClass: 'M1',
            segmentName: 'Breaking News',
            timeSlot: '07:00 - 09:00, 13:00 - 14:00, 20:00 - 21:00',
            days: ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY'],
            unitRate: 6000,
            totalSpots: 10,
            adForm: 'LIVE',
            rateCardId: 'rc-tv-announcements-006',
          },
        ],
      },
    ],
    createdAt: '2024-06-10T13:30:00Z',
    updatedAt: '2024-06-10T13:30:00Z',
  },
  {
    id: 'mp-007',
    campaignName: 'Real Estate Investment Expo',
    clientName: 'PropertyPro Ghana',
    campaignObjective: 'Event Promotion',
    targetAudience: 'High net worth individuals, age 35-65',
    expectedStartDate: '2024-10-15',
    expectedEndDate: '2024-10-31',
    totalBudget: 200000,
    budgetAllocated: 150000,
    status: 'paused',
    channels: [
      {
        mediaType: 'FM',
        channelName: 'Heaven Media House',
        segments: [
          {
            adType: 'INTERVIEWS',
            segmentClass: 'P1',
            segmentName: 'Evening Interview',
            timeSlot: '18:00 - 20:00',
            days: ['TUESDAY', 'THURSDAY'],
            unitRate: 7000,
            totalSpots: 4,
            rateCardId: 'rc-fm-interviews-003',
            programName: 'Business Evening',
          },
          {
            adType: 'JINGLES',
            segmentClass: 'A1',
            segmentName: 'Peak Jingle',
            timeSlot: '06:00 - 12:00, 16:00 - 21:00',
            days: ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY'],
            unitRate: 4500,
            totalSpots: 20,
            rateCardId: 'rc-fm-jingles-002',
          },
        ],
      },
    ],
    createdAt: '2024-05-20T10:30:00Z',
    updatedAt: '2024-06-15T09:00:00Z',
  },
];
